name: Build and test Products REST API

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: build and test products-api (Java ${{ matrix.java }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ 17 ]
    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v5

      # Step 2: Cache Maven dependencies
      - name: Set up Temurin JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: maven

      - name: Run tests
        run: ./mvnw clean test

      - name: Upload test reports (JUnit/Surefire)
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: surefire-reports-${{ matrix.java }}
          path: |
            **/target/surefire-reports/*.xml
            **/target/surefire-reports/*.txt
